---
title: "Homework 4"
subtitle: "Prof: Luiz Peternelli"
author: "Marco Guerra Hinostroza"
date: "`r Sys.Date()`"
format:
  html:
    embed-resources: true
    toc: true
    toc-location: left
    number-sections: false
    code-fold: false
    filters:
        - highlight-text
editor_options: 
  chunk_output_type: console
---

```{r}
library(readODS)
library(dplyr)
library(kableExtra)
```


# Question 1

Probability density function:

$$
f(x) = 
\begin{cases}
1 - x^2 + x^3 \quad ; \quad 0 \le x \le 1 \\
0 \quad ; \quad c.c
\end{cases}
$$
Since the area under the curve is different from 1, it is necessary to transform the density function.

$$
 \int_0^1 k(1-x^2+x^3) \, dx = 1
$$

$$
k \left( \int_0^1 1 \, dx - \int_0^1 x^2 \, dx + \int_0^1 x^3 \, dx \right) = 1
$$

$$
k = \frac{12}{11}
$$

Transformed function:

$$
f(x) = \frac{12}{11} \left(1 - x^2 + x^3 \right) \quad ; \quad 0 \le x \le 1
$$

### Simulation

To optimise the process we can graph the function and define a maximum value (m).
```{r}
curve((12/11)*(1 - x^2 + x^3), from = 0, to = 1)
```

Examining the graph we can take 1.1 as the maximum value.

```{r}
sim_ar <- function(n,m) {
  x <- numeric(n)
  #incluindo um contador para o tamanho da amostra
  i <- 0
  #incluindo um contador para o numero de pares de uniformes geradas
  j <- 0
  
  while (i < n) {
    # 1. Gerar x candidato da distribuição proposta (Uniforme[0, 1])
    xc <- runif(1, min = 0, max = 1)
    
    # 2. Gerar U da Uniforme[0, 1] para a aceitação
    U <- runif(1)
    
    f <- (12/11)*(1 - xc^2 + xc^3)
    
    # 3. Teste de aceitação
    if (U < f/m) {
      x[i+1] <- xc  # Aceita o valor candidato
      i <- i+1  # Incrementa o contador de aceitação
    }
    j <- j+1
  }
  cat("were generated ", j, "pair of uniforms ",fill=T)
  cat("to simulate ", i, " values of the random variable of interest ",fill=T)
  cat("ratio of efficiencx ",round((i/j)*100,2), "% ",fill=T)
  return(x)
}
```

```{r}
x_t <- sim_ar(1000, 1.1)
```

```{r}
hist(x_t, prob = TRUE)
curve((12/11)*(1 - x^2 + x^3), from = 0, to = 1, add = TRUE, col = "blue")
```

# Question 2

```{r, include=FALSE}
dt <- data <- read_ods("tabla.ods", sheet = 1, col_names = TRUE)
```

```{r,echo=FALSE}
colnames(dt) <- c("Z", "Y=0", "Y=1", "Y=0", "Y=1", "Y=0", "Y=1")

kbl(dt) |> 
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left") |> 
  add_header_above(c(" " = 1, "X = 0" = 2, "X = 1" = 2, "X = 2" = 2))
```

```{r}
# Valores de X e as probabilidades marginais associadas
valores_X <- c(1, 2, 3, 4)  # Substitua pelos valores de X da sua tabela
probabilidades_X <- c(0.1, 0.2, 0.4, 0.3)  # Substitua pelas probabilidades marginais de X

# Calculando a função de distribuição acumulada (FDA)
FDA_X <- cumsum(probabilidades_X)

# Criando um gráfico da FDA
plot(valores_X, FDA_X, type = "s", col = "#4682B4", 
     xlab = "Valores de X", ylab = "P(X)", 
     main = "Função de Distribuição Acumulada de X")

# Adicionando uma linha para indicar o comportamento acumulativo
lines(valores_X, FDA_X, type = "s", col = "#4682B4", lwd = 2)
```

